-- Tabela ALUNO
CREATE TABLE ALUNO (
    ID_ALUNO INT PRIMARY KEY,
    NOME VARCHAR(45),
    EMAIL VARCHAR(45),
    CPF BIGINT,
    ENDERECO VARCHAR(45),
    NUMERO INT,
    COMPLEMENTO VARCHAR(45),
    CIDADE VARCHAR(45),
    ESTADO VARCHAR(45)
);

-- Tabela PROFESSOR
CREATE TABLE PROFESSOR (
    ID_PROFESSOR INT PRIMARY KEY,
    NOME VARCHAR(45),
    EMAIL VARCHAR(45),
    CPF BIGINT,
    ENDERECO VARCHAR(45),
    NUMERO INT,
    COMPLEMENTO VARCHAR(45),
    CIDADE VARCHAR(45),
    ESTADO VARCHAR(45)
);

-- Tabela CURSO
CREATE TABLE CURSO (
    ID_CURSO INT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    ID_PROFESSOR INT,
    CONSTRAINT FK_CURSO_PROFESSOR FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSOR(ID_PROFESSOR)
);

-- Tabela CURSOALUNO (tabela de relacionamento)
CREATE TABLE CURSOALUNO (
    ID_CURSO INT,
    ID_ALUNO INT,
    CONSTRAINT FK_CURSOALUNO_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO),
    CONSTRAINT FK_CURSOALUNO_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID_ALUNO),
    PRIMARY KEY (ID_CURSO, ID_ALUNO) -- Chave composta
);
